Module #3
js-tasks-ru/vue-20211004_romashbis pull request #5
Opened 2022-02-02 23:35 UTC by romule

Здравствуйте. Закончил модуль №3 (прошу прощения что так долго, на работе релиз за релизом) - надеюсь грубых ошибок нет?

2022-02-02 23:36 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-03 12:17 UTC, ShGKme requested changes
В 03-MeetupCover ошибка при работе компонента. Остальные задачи приняты.

2022-02-03 12:17 UTC, ShGKme commented on 02-components/03-MeetupCover/MeetupCover.js
>      </div>`,
При отсутствии изображения не нужно добавлять никаких стилей. Можно пустую строку или любое falsy значение.

Но у вас с т.з. JS если изображения нет, то в качестве стилей требуется вывести "декремент переменно bg минус переменная url".  Что приводит к ошибке из-за отсутствия таких пероеменных.
![image](https://user-images.githubusercontent.com/25978914/152341051-616b78c8-afca-41de-8562-f6fcbdfc3e0e.png)

Скорее всего вы хотели передать это значение строкой. Но и строка `'--bg-url'` - это некорректный стиль.

2022-02-03 12:23 UTC, romule commented on 02-components/03-MeetupCover/MeetupCover.js
>      </div>`,
да - я уже у вас консультировался по этому вопросу.... поэтому перепроверю.

2022-02-12 10:29 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-12 16:41 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-02-12 16:42 UTC, merged